concuerror: add recipe
Concuerror [1] is a stateless model checking tool for Erlang programs. It
can be used to detect and debug concurrency errors, such as deadlocks
and errors due to race conditions. Moreover it can verify the absence of
such errors, because it tests programs systematically, unlike techniques
based on randomness.

1: https://concuerror.com/